version: "3.1"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    command: --serviceExecutor adaptive
    ##docker run yml file command
    ##docker-compose -f Desktop/department/src/main/resources/docker-compose.yml up -d
